### ISSUE TITLE
write issue

### ISSUE THREAD

**Issue by crusaderpi** [raumfisch/leosac-keytool#3]
Hi, I've installed the webui as per instructions and am able to login to the webui but can't add any data from the web end. Can you see any issues that may prevent data from being written?

**Comment by raumfisch** [comment]
Hey, can you check the output of `pm2 logs leosac-keytool` sounds like something is not working with the database connection.

What version of mongodb do you have installed?

**Comment by crusaderpi** [comment]
This is the output of logs:

[TAILING] Tailing last 15 lines for [leosac-keytool] process (change the value with --lines option)
/root/.pm2/logs/leosac-keytool-error.log last 15 lines:
0|leosac-k |     at connect (/home/pi/leosac-keytool/server/node_modules/mongodb/lib/core/connection/pool.js:580:14)
0|leosac-k |     at callback (/home/pi/leosac-keytool/server/node_modules/mongodb/lib/core/connection/connect.js:109:5)
0|leosac-k |     at runCommand (/home/pi/leosac-keytool/server/node_modules/mongodb/lib/core/connection/connect.js:140:7)
0|leosac-k |     at Connection.messageHandler (/home/pi/leosac-keytool/server/node_modules/mongodb/lib/core/connection/connect.js:334:5)
0|leosac-k |     at Connection.emit (events.js:198:13)
0|leosac-k |     at processMessage (/home/pi/leosac-keytool/server/node_modules/mongodb/lib/core/connection/connection.js:364:10)
0|leosac-k |     at Socket.<anonymous> (/home/pi/leosac-keytool/server/node_modules/mongodb/lib/core/connection/connection.js:533:15)
0|leosac-k |     at Socket.emit (events.js:198:13)
0|leosac-k |     at addChunk (_stream_readable.js:288:12)
0|leosac-k |     at readableAddChunk (_stream_readable.js:269:11)
0|leosac-k |     at Socket.Readable.push (_stream_readable.js:224:10)
0|leosac-k |     at TCP.onStreamRead [as onread] (internal/stream_base_commons.js:94:17)
0|leosac-k |   name: 'MongoNetworkError',
0|leosac-k |   errorLabels: [ 'TransientTransactionError' ],
0|leosac-k |   [Symbol(mongoErrorContextSymbol)]: {} }

/root/.pm2/logs/leosac-keytool-out.log last 15 lines:
0|leosac-k | GET /assets/css/icons.css 304 5.859 ms - -
0|leosac-k | GET /inline.1b94507ee65f80ecda7c.bundle.js 304 5.617 ms - -
0|leosac-k | GET /styles.9c0ad738f18adc3d19ed.bundle.css 304 5.580 ms - -
0|leosac-k | GET /polyfills.7510c6f44ab18600f35c.bundle.js 304 10.047 ms - -
0|leosac-k | GET /scripts.03e042f1f102bf0e2ed8.bundle.js 304 4.908 ms - -
0|leosac-k | GET /main.c950ca21177de719679e.bundle.js 304 3.166 ms - -
0|leosac-k | GET /assets/fonts/iconfont.woff2 304 1.483 ms - -
0|leosac-k | GET /api/groups - - ms - -
0|leosac-k | GET /api/users - - ms - -
0|leosac-k | GET /api/logs?offset=0&filter=&count=200 - - ms - -
0|leosac-k | GET /api/keys - - ms - -
0|leosac-k | GET / 302 1.912 ms - 56
0|leosac-k | GET /login 200 2.751 ms - 1330
0|leosac-k | GET /favicon.ico 302 1.466 ms - 28
0|leosac-k | GET /login 304 2.704 ms - -

Mongodb version: MongoDB shell version: 2.4.14

**Comment by raumfisch** [comment]
Sorry, i'm totally buisy right now, think i could find time on wednesday to try to reproduce this issue. Until then you could try to investigate more into the logs to see if there is maybe a more revealing error on startup of the application. 

See the logs while restarting the application with `pm2 restart leosac-keytool`
